### ISSUE TITLE
贴图丢失

### ISSUE THREAD

**Issue by jackwd387** [OoGodStaroO/VoidMatrix#3]
如题
![Screenshot_20240809-224019_Minecraft](https://github.com/user-attachments/assets/191f1e24-e89e-4110-ac40-8a3768d39ece)

**Comment by OoGodStaroO** [comment]
你是在Release下的吗

**Comment by jackwd387** [comment]
> 你是在Release下的吗

下载的源代码

**Comment by OoGodStaroO** [comment]
源代码忘记丢那张图了（
你下release的
